
steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile-gcp', '-t', 'gcr.io/$PROJECT_ID/file-ingest-front', '.']
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/custom-script-test2', '.']
images: ['gcr.io/$PROJECT_ID/file-ingest-front']

